import { test, expect } from '@playwright/test'

test('Agent governance persists an immutable version without execution', async ({ page }, testInfo) => {
  await page.setExtraHTTPHeaders({ 'X-ARC-Test-Client': 'agents' })
  const forbidden: string[] = []
  page.on('request', request => {
    if (!request.url().startsWith('http://127.0.0.1:48273/') || /test-runs|test-invocations|human-tasks/.test(request.url())) forbidden.push(request.url())
  })
  await page.goto('/w/synthetic/settings/model-providers')
  await page.getByLabel('邮箱').fill('browser@example.invalid')
  await page.getByLabel('密码').fill('Synthetic browser password 42!')
  await page.getByRole('button', { name: '登录', exact: true }).click()
  await page.getByLabel('名称', { exact: true }).fill('Agent browser provider')
  await page.getByLabel('Base URL', { exact: true }).fill('https://models.example.invalid/v1')
  await page.getByLabel('默认模型', { exact: true }).fill('synthetic-model')
  await page.getByLabel('Secret Ref（环境变量名）', { exact: true }).fill('SYNTHETIC_KEY')
  await page.getByRole('button', { name: '创建模型资产' }).click()
  await expect(page.getByText('模型资产已创建', { exact: true })).toBeVisible()
  await page.goto('/w/synthetic/settings/asset-library')
  await page.getByLabel('资产名称', { exact: true }).fill('Agent browser tool')
  await page.getByRole('button', { name: '创建资产', exact: true }).click()
  await expect(page.getByText('资产已创建', { exact: true })).toBeVisible()
  await page.goto('/w/synthetic/agents')
  await expect(page.getByText('Agent 迁移验证模式：仅资产治理，测试运行尚未迁移。')).toBeVisible()
  await page.getByRole('button', { name: '新建 Agent', exact: true }).click()
  await page.getByLabel('名称', { exact: true }).fill('Browser Agent original')
  await page.getByLabel('职责', { exact: true }).fill('Synthetic governance')
  await page.getByLabel('负责人', { exact: true }).fill('Synthetic team')
  await page.getByLabel('模型', { exact: true }).fill('synthetic-model')
  await page.getByRole('button', { name: '创建 Agent', exact: true }).click()
  await page.getByRole('link', { name: 'Browser Agent original', exact: true }).click()
  await page.getByRole('combobox', { name: '模型资产', exact: true }).selectOption({ label: 'Agent browser provider' })
  await page.getByLabel('Tools', { exact: true }).fill('Agent browser tool')
  await page.getByRole('button', { name: '保存草稿', exact: true }).click()
  await expect(page.getByText('草稿已保存', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: '发布新版本', exact: true }).click()
  await page.getByLabel('发布备注', { exact: true }).fill('Synthetic first version')
  await page.getByRole('button', { name: '确认发布版本', exact: true }).click()
  await expect(page.getByText('v1.0.0 已发布', { exact: true })).toBeVisible()
  await page.getByLabel('名称', { exact: true }).fill('Browser Agent edited')
  await page.getByRole('button', { name: '保存草稿', exact: true }).click()
  await expect(page.getByText('草稿已保存', { exact: true })).toBeVisible()
  await page.reload()
  await expect(page.getByLabel('名称', { exact: true })).toHaveValue('Browser Agent edited')
  await expect(page.locator('.version-item').getByText('Browser Agent original', { exact: true })).toBeVisible()
  await expect(page.getByRole('button', { name: '运行 Agent', exact: true })).toBeDisabled()
  await page.getByRole('button', { name: '停用 Agent', exact: true }).click()
  await page.reload()
  await expect(page.getByRole('button', { name: '保存草稿', exact: true })).toBeDisabled()
  await page.getByRole('button', { name: '启用 Agent', exact: true }).click()
  await page.reload()
  await expect(page.getByRole('button', { name: '保存草稿', exact: true })).toBeEnabled()
  await expect(page.locator('.version-item')).toHaveCount(1)
  await page.screenshot({ path: testInfo.outputPath('agent-governance.png'), fullPage: true })
  expect(forbidden).toEqual([])
})
