import { test, expect } from '@playwright/test'

test('same-database login and provider lifecycle without legacy calls', async ({ page }) => {
  await page.setExtraHTTPHeaders({ 'X-ARC-Test-Client': 'provider' })
  const external: string[] = [], unsupported: string[] = []
  page.on('request', request => {
    if (!request.url().startsWith('http://127.0.0.1:48273/')) external.push(request.url())
    if (/human-tasks|test-invocations|migrate-drafts|\/test$/.test(request.url())) unsupported.push(request.url())
  })
  await page.goto('/w/synthetic/settings/model-providers')
  await page.getByLabel('邮箱').fill('browser@example.invalid')
  await page.getByLabel('密码').fill('Synthetic browser password 42!')
  await page.getByRole('button', { name: '登录', exact: true }).click()
  await expect(page.getByRole('heading', { name: '模型资产', level: 2, exact: true })).toBeVisible()
  await expect(page.getByText('隔离迁移验证', { exact: true })).toBeVisible()
  await page.getByLabel('名称', { exact: true }).fill('Browser provider')
  await page.getByLabel('Base URL', { exact: true }).fill('https://models.example.invalid/v1')
  await page.getByLabel('默认模型', { exact: true }).fill('synthetic')
  await page.getByLabel('Secret Ref（环境变量名）', { exact: true }).fill('SYNTHETIC_KEY')
  await page.getByRole('button', { name: '创建模型资产' }).click()
  await expect(page.getByText('模型资产已创建', { exact: true })).toBeVisible()
  await expect(page.locator('article').filter({ has: page.getByRole('button', { name: '编辑 Browser provider', exact: true }) })
    .getByText('model_provider.create', { exact: true })).toBeVisible()
  await page.reload()
  await expect(page.getByRole('button', { name: '测试连接 Browser provider' })).toBeDisabled()
  await page.getByRole('button', { name: '编辑 Browser provider' }).click()
  await page.getByLabel('编辑名称', { exact: true }).fill('Browser provider edited')
  await page.getByRole('button', { name: '保存 Browser provider', exact: true }).click()
  await expect(page.getByText('模型资产已更新', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: '停用 Browser provider edited' }).click()
  await page.reload()
  await expect(page.getByRole('button', { name: '停用 Browser provider edited' })).toBeDisabled()
  expect(external).toEqual([])
  expect(unsupported).toEqual([])
})

test('tool registration persists edits and audit without execution', async ({ page }, testInfo) => {
  await page.setExtraHTTPHeaders({ 'X-ARC-Test-Client': 'tool' })
  const invalidRequests: string[] = []
  page.on('request', request => {
    if (!request.url().startsWith('http://127.0.0.1:48273/')
      || /human-tasks|test-invocations/.test(request.url())) invalidRequests.push(request.url())
  })
  await page.goto('/w/synthetic/settings/asset-library')
  await page.getByLabel('邮箱').fill('browser@example.invalid')
  await page.getByLabel('密码').fill('Synthetic browser password 42!')
  await page.getByRole('button', { name: '登录', exact: true }).click()
  await page.getByLabel('资产名称', { exact: true }).fill('Browser tool')
  await page.getByLabel('适配类型', { exact: true }).selectOption('http')
  await page.getByLabel('HTTP 地址', { exact: true }).fill('https://tools.example.invalid/run')
  await page.getByLabel('HTTP 方法', { exact: true }).selectOption('GET')
  await page.getByRole('button', { name: '创建资产', exact: true }).click()
  await expect(page.getByText('资产已创建', { exact: true })).toBeVisible()
  await expect(page.locator('article').filter({ has: page.getByRole('button', { name: '编辑 Browser tool', exact: true }) })
    .getByText('tool_skill_asset.create', { exact: true })).toBeVisible()
  await page.reload()
  await expect(page.getByRole('button', { name: '测试调用 Browser tool' })).toBeDisabled()
  await page.getByRole('button', { name: '编辑 Browser tool', exact: true }).click()
  await expect(page.getByLabel('编辑HTTP 地址')).toHaveValue('https://tools.example.invalid/run')
  await expect(page.getByLabel('编辑HTTP 方法')).toHaveValue('GET')
  await page.getByLabel('编辑资产名称').fill('Browser tool edited')
  await page.getByRole('button', { name: '保存 Browser tool', exact: true }).click()
  await expect(page.getByText('资产已更新', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: '停用 Browser tool edited', exact: true }).click()
  await expect(page.getByText('资产已停用', { exact: true })).toBeVisible()
  await page.reload()
  await expect(page.getByRole('button', { name: '停用 Browser tool edited', exact: true })).toBeDisabled()
  await expect(page.getByText('tool_skill_asset.deactivate', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: '停用 Browser tool edited', exact: true }).scrollIntoViewIfNeeded()
  await page.screenshot({ path: testInfo.outputPath('tool-lifecycle.png'), fullPage: true })
  expect(invalidRequests).toEqual([])
})

test('nonempty persisted references and hidden invocation summaries', async ({ page }) => {
  await page.setExtraHTTPHeaders({ 'X-ARC-Test-Client': 'references' })
  await page.goto('/w/synthetic/settings/model-providers')
  await page.getByLabel('邮箱').fill('browser@example.invalid')
  await page.getByLabel('密码').fill('Synthetic browser password 42!')
  await page.getByRole('button', { name: '登录', exact: true }).click()
  const provider = page.locator('article').filter({ hasText: 'Referenced provider' })
  await expect(provider.getByText('Agent 草稿 1', { exact: true })).toBeVisible()
  await expect(provider.getByText('发布版本 1', { exact: true })).toBeVisible()
  await page.goto('/w/synthetic/settings/asset-library')
  const asset = page.locator('article').filter({ hasText: 'Referenced tool' })
  await expect(asset.getByText('草稿 Agent 1', { exact: true })).toBeVisible()
  await expect(asset.getByText('已发布版本 1', { exact: true })).toBeVisible()
  await expect(asset.getByText('tool_skill_asset.invocation', { exact: true })).toBeVisible()
  await expect(page.getByText('内容已隐藏（迁移安全策略）', { exact: false }).first()).toBeVisible()
  await expect(page.locator('body')).not.toContainText('synthetic-private-input')
  await expect(page.locator('body')).not.toContainText('synthetic-private-output')
})
