import { test, expect } from '@playwright/test'

test('rubric migration creates and publishes a template without execution APIs', async ({ page }, testInfo) => {
  const forbidden: string[] = []
  page.on('request', request => {
    if (!request.url().startsWith('http://127.0.0.1:48273/') || /test-runs|test-invocations|regression-runs/.test(request.url())) forbidden.push(request.url())
  })
  await page.goto('/w/synthetic/evaluations/new')
  await page.getByLabel('邮箱').fill('browser@example.invalid')
  await page.getByLabel('密码').fill('Synthetic browser password 42!')
  await page.getByRole('button', { name: '登录', exact: true }).click()
  await expect(page.getByText(/量规迁移验证模式/)).toBeVisible()
  await page.getByLabel('模板名称', { exact: true }).fill('Browser rubric')
  await page.getByLabel('适用产出物', { exact: true }).fill('Report')
  await page.getByLabel('硬性门禁', { exact: true }).fill('Grounded sources')
  await page.getByLabel('维度 1 名称', { exact: true }).fill('Quality')
  await page.getByLabel('维度 1 评分标准', { exact: true }).fill('Has evidence')
  const creating = page.waitForResponse(response => response.url().endsWith('/evaluations/rubrics') && response.request().method() === 'POST')
  await page.getByRole('button', { name: '保存模板', exact: true }).click()
  expect((await creating).status()).toBe(201)
  await expect(page.getByRole('region', { name: '管理评估模板' })).toBeVisible()
  await expect(page.getByLabel('模板名称', { exact: true })).toHaveValue('Browser rubric')
  await page.getByRole('button', { name: '发布版本', exact: true }).click()
  await expect(page.getByText('已发布不可变版本 v1.0.0', { exact: true })).toBeVisible()
  await page.reload()
  await expect(page.getByLabel('模板名称', { exact: true })).toHaveValue('Browser rubric')
  await expect(page.getByText('版本 v1.0.0', { exact: true })).toBeVisible()
  await page.getByLabel('通过分数', { exact: true }).fill('95')
  await page.getByRole('button', { name: '保存模板', exact: true }).click()
  await expect(page.getByText('评估模板已保存', { exact: true })).toBeVisible()
  const history = page.waitForResponse(response => response.url().endsWith('/versions') && response.request().method() === 'GET')
  await page.getByRole('button', { name: '发布版本', exact: true }).click()
  await expect(page.getByText('已发布不可变版本 v1.1.0', { exact: true })).toBeVisible()
  const versions = await (await history).json()
  expect(versions.map((version: { version: string; snapshot: { passScore: number } }) => [version.version, version.snapshot.passScore]))
    .toEqual([['v1.1.0', 95], ['v1.0.0', 85]])
  await page.getByRole('button', { name: '停用模板', exact: true }).click()
  await expect(page.getByText('评估模板已停用', { exact: true })).toBeVisible()
  await page.reload()
  await expect(page.getByLabel('通过分数', { exact: true })).toHaveValue('95')
  await expect(page.getByRole('button', { name: '保存模板', exact: true })).toBeDisabled()
  await expect(page.getByRole('button', { name: '发布版本', exact: true })).toBeDisabled()
  await expect(page.getByText('版本 v1.0.0', { exact: true })).toBeVisible()
  await expect(page.getByText('版本 v1.1.0', { exact: true })).toBeVisible()
  await page.screenshot({ path: testInfo.outputPath('rubric-governance.png'), fullPage: true })
  expect(forbidden).toEqual([])
})
